### ISSUE TITLE
Change absolute path to relative path

### ISSUE THREAD

**Issue by mcworkaholic** [mcworkaholic/IS345-G5-Music-Player#10]
At line 164 of [Config.cs](https://github.com/mcworkaholic/IS345-G5-Music-Player/blob/main/Music%20Player/Config.cs) there's an absolute path that needs to be changed to relative for it to work on other user's pc's.

**Comment by HillFlorence** [comment]
solution  add to file 👍   
using System.IO;

 var path = ".";
var fullPath = Path.GetFullPath(path);

**Comment by mcworkaholic** [comment]
@HillFlorence, Did you test the functionality after you made these changes? Because:
``var path = ".";
  var fullPath = Path.GetFullPath(path);
``

yields: ``C:\Users\Weston\Desktop\Music-Player\IS345-G5-Music-Player-Origin\Music Player\bin\Debug``

when the output should be: ``C:\Users\<username>\Desktop\Music-Player\IS345-G5-Music-Player-Origin\Music Player\Utilities``

Here, we are trying to get the relative path to the "Utilities" folder contained within the project's directory.

**Comment by HillFlorence** [comment]
Goodmorning.
Sounds good. Will work on some more issues tonight.

________________________________
