### ISSUE TITLE
form corners

### ISSUE THREAD

**Issue by mcworkaholic** [mcworkaholic/IS345-G5-Music-Player#6]
all form corners should have a slightly rounded edge to them, this isn't the 80's

**Comment by ahmedii10** [comment]
will work on this

**Comment by ahmedii10** [comment]
You can update the albumArtBox_Click and albumArtBox_DoubleClick methods in your code with the following code to implement the requested functionality:


private bool albumPanelVisible = false;

private void albumArtBox_Click(object sender, EventArgs e)
{
    if (WindowsMediaPlayer.playState == WMPLib.WMPPlayState.wmppsPlaying)
    {
        // Show album panel
        ViewAlbum(rootNode.FindNodeByFullPath(WindowsMediaPlayer.URL, songObj).Parent);
        albumPanelVisible = true;
    }
}

private void albumArtBox_DoubleClick(object sender, EventArgs e)
{
    // Toggle visibility of album art box
    albumArtBox.Visible = !albumArtBox.Visible;

    // Hide album panel if it is visible
    if (albumPanelVisible)
    {
        albumPanel.Visible = false;
        treeView.Visible = false;
        backBox.Visible = false;
        librarylistBox.Visible = true;
        albumPanelVisible = false;
    }
}

**Comment by mcworkaholic** [comment]
Please follow the instructions in [CONTRIBUTING.md](https://github.com/mcworkaholic/IS345-G5-Music-Player/blob/main/CONTRIBUTING.md) before commenting on an issue. If you don't know how to do something, I will happily set-up a Zoom session. In addition, You are commenting under the wrong issue.
