### ISSUE TITLE
progress bar during directory traversal

### ISSUE THREAD

**Issue by mcworkaholic** [mcworkaholic/IS345-G5-Music-Player#7]
For: [Config.cs](https://github.com/mcworkaholic/IS345-G5-Music-Player/blob/main/Music%20Player/Config.cs)

There should be a progress bar indicating how far the search is along when the user clicks on "Locate Audio" / "Locate Audio Files", inputs a directory hint, and presses the enter key so they aren't left wondering if their program crashed.

**Comment by ahmedii10** [comment]
private void LocateAudioButton_Click(object sender, EventArgs e)
{
    string directoryHint = DirectoryHintTextBox.Text;
    if (string.IsNullOrWhiteSpace(directoryHint) || !Directory.Exists(directoryHint))
    {
        MessageBox.Show("Please enter a valid directory hint.", "Invalid Directory Hint", MessageBoxButtons.OK, MessageBoxIcon.Error);
        return;
    }

    // Get audio files in the specified directory and subdirectories
    string[] audioFiles = Directory.GetFiles(directoryHint, "*.mp3", SearchOption.AllDirectories);

    // Initialize the progress bar
    AudioFilesProgressBar.Minimum = 0;
    AudioFilesProgressBar.Maximum = audioFiles.Length;
    AudioFilesProgressBar.Value = 0;
    AudioFilesProgressBar.Step = 1;
    AudioFilesProgressBar.Visible = true;

    foreach (string audioFile in audioFiles)
    {
        // Update the progress bar
        AudioFilesProgressBar.PerformStep();

        // Process the audio file
        // ...
    }

    // Hide the progress bar
    AudioFilesProgressBar.Visible = false;
}

**Comment by mcworkaholic** [comment]
Please follow the instructions in [CONTRIBUTING.md](https://github.com/mcworkaholic/IS345-G5-Music-Player/blob/main/CONTRIBUTING.md) before commenting on an issue. If you don't know how to do something, I will happily set-up a Zoom session.

**Comment by mcworkaholic** [comment]
Changed from progress bar to a simple label for display
